<?php $this->headMeta()->appendName('description', "Il y a rien sur cette page"); ?>
<?php $this->headTitle("À propos"); ?>

<section class="white unique-section">
    <div class="container">
        <div class="row-fluid">
            <div class="offset2 span10">
                <h1>Test Développeur</h1>
                <h2>Par Maxence Minguet</h2>
            </div>
        </div>
     </div>
</section>
